<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>

		<InterceptorsNamespaces>
			$(InterceptorsNamespaces);
			Microsoft.Extensions.Configuration.Binder.SourceGeneration
		</InterceptorsNamespaces>

		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	</PropertyGroup>

	

	<ItemGroup>
		<PackageReference Include="Cacx.LanguageManager" Version="1.1.2" />
		<PackageReference Include="Cristiano3120.Logger" Version="1.0.7" />
		<PackageReference Include="DnsClient" Version="1.8.0" />
		<PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.0" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.0" />
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.0" />
		<PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\CacxShared\CacxShared.csproj" />
	</ItemGroup>

	<ItemGroup>
		<SplashScreen Include="SplashScreen.gif" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Resources\Login\Login.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>Login.resx</DependentUpon>
		</Compile>
		<Compile Update="Resources\Register\Register.Designer.cs">
		  <DesignTime>True</DesignTime>
		  <AutoGen>True</AutoGen>
		  <DependentUpon>Register.resx</DependentUpon>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Update="Resources\Login\Login.resx">
			<Generator>ResXFileCodeGenerator</Generator>
			<LastGenOutput>Login.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<EmbeddedResource Update="Resources\Register\Register.resx">
		  <Generator>ResXFileCodeGenerator</Generator>
		  <LastGenOutput>Register.Designer.cs</LastGenOutput>
		</EmbeddedResource>
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Resources\Themes\" />
	</ItemGroup>
</Project>
