// <auto-generated />
using System;
using CacxServer.UserDataDatabaseResources;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CacxServer.Migrations
{
    [DbContext(typeof(UserDataDbContext))]
    [Migration("20251013211808_ReserveTableUsernameUpdate")]
    partial class ReserveTableUsernameUpdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CacxServer.UserDataDatabaseResources.DbUser", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Biography")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("Birthday")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("Email")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("EmailHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("FirstName")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("LastName")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("ProfilePictureUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EmailHash")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CacxServer.UserDataDatabaseResources.DbUserUniequeData", b =>
                {
                    b.Property<byte[]>("EmailHash")
                        .HasColumnType("bytea");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("EmailHash");

                    b.HasIndex("EmailHash")
                        .IsUnique();

                    b.HasIndex("Username");

                    b.ToTable("ReservedUserData");
                });
#pragma warning restore 612, 618
        }
    }
}
